### ISSUE TITLE
Rename caf.core

### ISSUE THREAD

**Issue by MattBuckley-TfN** [Transport-for-the-North/caf.base#61]
We can't use caf.core on PyPI because

> The name 'caf.core' is too similar to an existing project.

I think the project which is causing the issue is [cafcore](https://pypi.org/project/cafcore/).

Looking at a thesaurus for some suggestions my current favourite is `caf.crux`, I don't think it's as informative as `caf.core` but its nice a succinct and doesn't look like we will have an issue using it on PyPI or conda-forge

@isaac-tfn, @BenTaylor-TfN - any thoughts on the name change?

**Comment by BenTaylor-TfN** [comment]
That's frustrating! Part of the reason for choosing the CAF namespace was to avoid issues like this. 

I wasn't aware that PyPI did this, so I did some digging into how it does it. [This](https://stackoverflow.com/questions/71489687/pypi-the-name-is-too-similar-to-an-existing-project) explains it, but the important part is:
* PyPI has an `ultranormalize_name` function that is used to check for similar names with the following process
  1. Both cases of `o` (lower and upper case, `o` and `O`) gets replaced with `0` (e.g., `caf.core` is the same as `caf.cOre` and `caf.c0re`)
  2. Both cases of `L` and `I` are replaced with `1` (e.g., `example` is same as `examp1e` and `exampie`)
  3. All `.`, `_`, and `-` characters are removed (e.g., `e-x-a-m-p-l-e` is same as `example`)
  4. The result is then lowercased and compared to the already existing names

Something to consider and check going forward for future package names.

As far as naming goes, I've got no strong opinions. @chrisbstorey is normally good at this one! I could be tempted by caf.kernel, but that could be misleading with the kernel used in the ML stuff we could be picking up in future.
