### ISSUE TITLE
IPF adjustment errors out on non-DVector adjustments

### ISSUE THREAD

**Issue by asongtoruin** [Transport-for-the-North/caf.base#71]
We again had an error when trying to run with the `ipf_adjustment_fixes` branch, namely with the following section:

https://github.com/Transport-for-the-North/caf.base/blob/0e499aeb07206eb03e70bbc982297979ee4e4686/src/caf/base/data_structures.py#L2284-L2291

The logical issue I see is that:
- `adj` is a `pandas` object - not sure if it's a `Series` or `DataFrame`, but it kind of doesn't matter here
- `adj = agg_1 / agg_2`, so it follows that `agg_1` and `agg_2` are likely also both the same kind of `pandas` object
- We're trying to access a `.zoning_system` attribute of these two - which they don't have because they aren't `DVector`

I had assumed last night that we simply needed to swap in the appropriate `target` variables (which _are_ `DVector`) with an extra fix to handle translation columns being lowercase, i.e.

```python
                elif isinstance(adj, pd.Series):
                    adj = translation.pandas_vector_zone_translation(adj,
                                                                     trans,
                                                                     f"{target_2.zoning_system.name.lower()}_id",
                                                                     f"{target_1.zoning_system.name.lower()}_id",
                                                                     target_1.zoning_system.translation_column_name(
                                                                         target_2.zoning_system),
                                                                     False)
```

But checking the `pandas_vector_zone_translation` code, I think that may be incorrect too - `target_1.zoning_system.translation_column_name(target_2.zoning_system)` will I think give us the `target_1_to_target_2` column and it looks like `pandas_vector_zone_translation` uses these as _multiplication_ factors ([here](https://github.com/Transport-for-the-North/caf.toolkit/blob/ab9ac797151fb70ca7976294ed189c2e74c86750/src/caf/toolkit/translation.py#L899-L901))

So I'm not sure whether the last line should be

```python
                elif isinstance(adj, pd.Series):
                    adj = translation.pandas_vector_zone_translation(adj,
                                                                     trans,
                                                                     f"{target_2.zoning_system.name.lower()}_id",
                                                                     f"{target_1.zoning_system.name.lower()}_id",
                                                                     target_2.zoning_system.translation_column_name(
                                                                         target_1.zoning_system),
                                                                     False)
```

i.e. using the `target_2_to_target_1` translation column instead, though I guess the fact that my correct seemed to run without issue might suggest it's okay? @isaac-tfn, any thoughts?

**Comment by isaac-tfn** [comment]
Hi Adam, thanks for rasising, on the first point of agg_1 and agg_2 sharing type with adj, you're right apologies, I'll change that now to reference target_1/2 instead which will always be DVectors.

On the second point, this is confusing to read so I should have commented. Here because it is factors being disaggregated we want to use the 'wrong' column, so that all of the factors in the trans vector are 1. If the 'correct' column is used the factors being disaggregated. It's worth double checking but I'm pretty sure this bit is correct.

Have you made the first fix (agg change to target) and are running?

**Comment by isaac-tfn** [comment]
Great ok, Would you rather open a PR for that change yourself or I just add the same to mine?

**Comment by asongtoruin** [comment]
This change doesn't appear to have been pushed yet?

**Comment by isaac-tfn** [comment]
Sorry I think I had the wrong repo active in github app yesterday and made a commit somewhere else with a nonsensical commit message, should be there now
